config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # вложенные ресурсы: ответ вложен в вопрос
  resources :questions, shallow: true do
    resources :answers
  end

  root to: "questions#index"
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user

  validates :body, presence: true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers, dependent: :destroy

  validates :title, :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def author_of?(obj)
    self.id == obj.user_id
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :load_question, only: [:create]
  before_action :load_answer, only: [:edit, :update, :destroy]

  def edit
  end

  def update
    if current_user&.author_of? @answer
    #if current_user.id == @answer.user_id
    @answer.update(answer_params)
    @question = @answer.question
    end
  end

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user
    @answer.save
  end

  def destroy
    @question = @answer.question
    if current_user.author_of? @answer
      @answer.destroy!
      flash[:notice] = 'Your answer was successfully deleted.'
      redirect_to question_path(@question)
    else
      redirect_to question_path(@question)
    end
  end

  private

  def load_question
    @question = Question.find(params[:question_id])
  end

  def load_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :load_question, only: [:show, :edit, :update, :destroy]

  def index
    @questions = Question.all
  end

  def show

  end

  def new
    @question = Question.new
  end

  def edit

  end

  def create
    @question = current_user.questions.new(question_params)
    if @question.save
      flash[:notice] = 'Your question was successfully created.'
      redirect_to @question
    else
      render :new
    end
  end

  def update
    if @question.update(question_params)
      redirect_to @question
    else
      render :edit
    end
  end

  def destroy
    if current_user.author_of? @question
      @question.destroy
      flash[:notice] = 'Your question was successfully deleted.'
      redirect_to questions_path
    else
      redirect_to questions_path
    end
  end

  private

  def load_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_answer.html.slim
- if answer.persisted?
  div class="answer-#{answer.id}"
    = answer.body
    - if current_user&.author_of? answer
      p= link_to 'Edit', '', class: 'edit-answer-link', data: { answer_id: answer.id }
      p= link_to "delete answer", answer_path(answer), method: :delete
      p
      = form_for [answer], remote: true, html: { id: "edit-answer-#{answer.id}"} do |f|
        = f.label :body, "Answer"
        = f.text_area :body
        = f.submit 'Save'

app/views/answers/_answers.html.slim
- @question.answers.each do |answer|
  div class="answer-#{answer.id}"
    - if answer.persisted?
      p= answer.body
      - if current_user&.author_of? answer
        p= link_to 'Edit', '', class: 'edit-answer-link', data: { answer_id: answer.id }
        p= link_to "delete answer", answer_path(answer), method: :delete
        p
        = form_for [answer], remote: true, html: { id: "edit-answer-#{answer.id}"} do |f|
          = f.label :body, "Answer"
          = f.text_area :body
          = f.submit 'Save'

app/views/answers/_form.html.slim
= form_for [@question, Answer.new], remote: true, html: { id: "new_answer"} do |f|
   p= f.label :body, 'Answer'
   p= f.text_area :body
   p= f.submit 'Post your answer'

app/views/answers/create.js.erb
$('.answers').append('<%= j render @answer %>');
$('form#new_answer #answer_body').val('');
$('.errors').html("<%= j render 'shared/errors', object: @answer %>");

app/views/answers/update.js.erb
<% if @answer.errors.present? %>
    <% @answer.errors.full_messages.each do |message| %>
        $('.errors').html('<%= j message %>');
    <% end %>
<% else %>
  $('#answer<%= @answer.id %>').replaceWith('<%= j render @answer %>');
  $('.answers').html("<%= j render 'answers' %>");
  $('.edit-answer-link').click(function(e) {
    e.preventDefault();
    $(this).hide();
    answer_id = $(this).data('answerId');
    $('form#edit-answer-' + answer_id).show();
});
<% end %>

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title QnA
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    div= link_to "QnA", root_path
    - if user_signed_in?
      ul
        li= link_to 'Sign out', destroy_user_session_path, method: :delete
    - else
      ul
        li= link_to 'Sign up', new_user_registration_path
        li= link_to 'Sign in', new_user_session_path
    p.notice= notice
    p.alert= alert
    = yield
 

app/views/questions/index.html.slim
h1 All Questions

p = link_to 'Ask question', new_question_path

-@questions.each do |question|
  h3= link_to question.title, question

app/views/questions/new.html.slim
h2 New Question
= form_for @question do |f|
  p
  = render 'shared/errors', object: @question
  p
  = f.label :title
  p
  = f.text_field :title
  p
  = f.label :body
  p
  = f.text_area :body
  p
  = f.submit 'Create'

app/views/questions/show.html.slim
h1 = @question.title
p = @question.body

- if current_user&.author_of? @question
  = link_to "delete question", question_path(@question), method: :delete

h2 Answers
.answers
   = render 'answers/answers'
 
- if user_signed_in?
  .errors
= render 'answers/form'

app/views/shared/_errors.html.slim
- if object && object.errors.any?

    strong= pluralize(object.errors.count, "error")
    | :&nbsp;
    ul
      - object.errors.full_messages.each do |message|
        li= message